### ISSUE TITLE
Issues with PSP games

### ISSUE THREAD

**Issue by Double-0-seven7** [openspy/openspy-core#14]
There are about 4  PSP games that still dont work via Openspy yet.
2 games that I tried recently (yesterday) are : 

- Worms Battle Islands
- Infected

These games have issues seeing other players in the lobby and connect to them.
For Worms Battle Islands the game could crash the PSP for at least 1 player after the game is about to start.

In the past I tried 2 other games and they are : 

- Marvel Trading Card Game - Can't create or use an account to connect , thankfully the game got a LAN mode that is easy to use.
- Warhammer 40,000: Tactics - Can't establish a connection between games properly.

**Comment by Double-0-seven7** [comment]
OK seems like Worms works now and doesn't crash anymore. (still buggy in places though).

**Comment by Double-0-seven7** [comment]
May be a related issue to WWE 06 on PS2 which got matchmaking issues that are similar.

**Comment by chc** [comment]
These issues should be resolved now, if not reopen and let me know. Thanks for reporting and my bad on the delay answering this.

**Comment by Double-0-seven7** [comment]
@chc Warhammer still doesn't work I think its the only one left...
I don't remember whats going on with Marvel TCG but I just remember i couldn't login or create an account at all.
